## pandas
특정 데이터를 DataFrame형식으로 처리

In [5]:
import pandas as pd

In [10]:
df = pd.read_csv("../data_set/1.pandas/1.pandas.csv")
df

In [13]:
print(df['name'])
df.age

0     Kim
1     Cho
2    Choi
3      jo
Name: name, dtype: object

0    20
1    30
2    40
3    50
Name: age, dtype: int64

In [15]:
#df[["name", "age"]]
df[["name"]]

   name
0   Kim
1   Cho
2  Choi
3    jo

In [17]:
df

   name  score grade  age
0   Kim  100.0     A   20
1   Cho   95.0     A   30
2  Choi   90.5     B   40
3    jo   85.7     B   50

In [19]:
#df[ 1 : 3 ] 
df[ 1 : ] # 1 ~ 끝까지

   name  score grade  age
1   Cho   95.0     A   30
2  Choi   90.5     B   40
3    jo   85.7     B   50

In [20]:
df[ 1 : 3 ]#['name']

   name  score grade  age
1   Cho   95.0     A   30
2  Choi   90.5     B   40

In [28]:
# index(조건), column(조건)
df.loc[ 1 : 3 , "name" ] = "aaaa"
df

   name  score grade  age
0   Kim  100.0     A   20
1  aaaa   95.0     A   30
2  aaaa   90.5     B   40
3  aaaa   85.7     B   50

In [29]:
df = pd.read_csv("../data_set/1.pandas/1.pandas.csv")
df

   name  score grade  age
0   Kim  100.0     A   20
1   Cho   95.0     A   30
2  Choi   90.5     B   40
3    jo   85.7     B   50

In [31]:
df.loc[ :  , ['name','age'] ]

   name  age
0   Kim   20
1   Cho   30
2  Choi   40
3    jo   50

In [48]:
df.loc[ : ]

   name  score grade  age
0   Kim  100.0     C   20
1   Cho   95.0     C   30
2  Choi   90.5     B   40
3    jo   85.7     B   50

In [49]:
df = pd.read_csv("../data_set/1.pandas/1.pandas.csv")
df

   name  score grade  age
0   Kim  100.0     A   20
1   Cho   95.0     A   30
2  Choi   90.5     B   40
3    jo   85.7     B   50

In [50]:
df.loc[ df['grade'] == 'A']

  name  score grade  age
0  Kim  100.0     A   20
1  Cho   95.0     A   30

In [51]:
df.loc[ df['grade'] == 'A', 'grade']

0    A
1    A
Name: grade, dtype: object

In [58]:
df.loc[ df['grade'] == 'A', 'grade' ] == 'CCC'
df

   name  score grade  age
0   Kim  100.0     A   20
1   Cho   95.0     A   30
2  Choi   90.5     B   40
3    jo   85.7     B   50

In [59]:
df.drop(2)

  name  score grade  age
0  Kim  100.0     A   20
1  Cho   95.0     A   30
3   jo   85.7     B   50

In [60]:
df

   name  score grade  age
0   Kim  100.0     A   20
1   Cho   95.0     A   30
2  Choi   90.5     B   40
3    jo   85.7     B   50

In [61]:
df = df.drop(2)
df

  name  score grade  age
0  Kim  100.0     A   20
1  Cho   95.0     A   30
3   jo   85.7     B   50

In [62]:
df.drop(1, inplace = True)
df

  name  score grade  age
0  Kim  100.0     A   20
3   jo   85.7     B   50

In [63]:
df.drop(0, axis=0, inplace=True)
df

  name  score grade  age
3   jo   85.7     B   50

In [64]:
df.drop('name', axis=1, inplace=True)
df

   score grade  age
3   85.7     B   50

In [65]:
df = pd.read_csv("../data_set/1.pandas/1.pandas.csv")
df

   name  score grade  age
0   Kim  100.0     A   20
1   Cho   95.0     A   30
2  Choi   90.5     B   40
3    jo   85.7     B   50

In [67]:
df['score'] < 95

0    False
1    False
2     True
3     True
Name: score, dtype: bool

In [69]:
#df[df['score'] < 95]
df.loc[df['score'] < 95]

   name  score grade  age
2  Choi   90.5     B   40
3    jo   85.7     B   50

In [70]:
#df[df['score'] < 95]['name']
df.loc[df['score'] < 95, 'name']

2    Choi
3      jo
Name: name, dtype: object

In [72]:
#df[df['score'] < 95]['name','age']]
df.loc[df['score'] < 95, ['name','age']]

   name  age
2  Choi   40
3    jo   50

In [74]:
df.columns

Index(['name', 'score', 'grade', 'age'], dtype='object')

In [75]:
df.values

array([['Kim', 100.0, 'A', 20],
       ['Cho', 95.0, 'A', 30],
       ['Choi', 90.5, 'B', 40],
       ['jo', 85.7, 'B', 50]], dtype=object)

In [77]:
df.dtypes

name      object
score    float64
grade     object
age        int64
dtype: object

In [78]:
df['grade']

0    A
1    A
2    B
3    B
Name: grade, dtype: object

In [79]:
df['grade'].isin(['A']) # isin:해당 값이 있는지 확인

0     True
1     True
2    False
3    False
Name: grade, dtype: bool

In [80]:
df[df['grade'].isin(['A'])]

  name  score grade  age
0  Kim  100.0     A   20
1  Cho   95.0     A   30

In [81]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [83]:
index_name = ['김','이','박','조']
df.index = index_name

In [84]:
df

   name  score grade  age
김   Kim  100.0     A   20
이   Cho   95.0     A   30
박  Choi   90.5     B   40
조    jo   85.7     B   50

In [85]:
df.index

Index(['김', '이', '박', '조'], dtype='object')

In [86]:
df[1:3]

   name  score grade  age
이   Cho   95.0     A   30
박  Choi   90.5     B   40

In [87]:
df[ '이' : '조' ]

   name  score grade  age
이   Cho   95.0     A   30
박  Choi   90.5     B   40
조    jo   85.7     B   50