In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../../data_set/2.데이터 클린징/nan.csv")
df

   data1  data2  data3  nan_1  nan_2
0      0      1      2    1.7    NaN
1      3      4      2    NaN    NaN
2      3      4      8    2.4    NaN
3      9     10     11    NaN    NaN
4     12     10     14    1.2    NaN
5     15     16     17    NaN    1.0

In [3]:
df.replace(to_replace=2, value=200)

   data1  data2  data3  nan_1  nan_2
0      0      1    200    1.7    NaN
1      3      4    200    NaN    NaN
2      3      4      8    2.4    NaN
3      9     10     11    NaN    NaN
4     12     10     14    1.2    NaN
5     15     16     17    NaN    1.0

In [5]:
import numpy as np
df.replace(to_replace=np.nan, value="변경값")

   data1  data2  data3 nan_1 nan_2
0      0      1      2   1.7   변경값
1      3      4      2   변경값   변경값
2      3      4      8   2.4   변경값
3      9     10     11   변경값   변경값
4     12     10     14   1.2   변경값
5     15     16     17   변경값   1.0

In [6]:
df.replace(to_replace={"nan_2":np.nan}, value="치환", inplace=True)
df

   data1  data2  data3  nan_1 nan_2
0      0      1      2    1.7    치환
1      3      4      2    NaN    치환
2      3      4      8    2.4    치환
3      9     10     11    NaN    치환
4     12     10     14    1.2    치환
5     15     16     17    NaN   1.0

In [9]:
df = pd.read_csv("../../data_set/2.데이터 클린징/bicycle.csv")
df.head()

,자전거번호,대여일시,대여소번호,대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리,나이
0,SPB-23220,2019-11-01 8:48,646,장한평역 1번출구 (국민은행앞),3.0,2019-11-01 9:01,3,중랑센터,7.0,12.0,1100.0,50
1,SPB-16216,2019-11-04 8:38,646,장한평역 1번출구 (국민은행앞),2.0,2019-11-04 8:56,3,중랑센터,2.0,7.0,1420.0,31
2,SPB-21097,2019-11-04 8:46,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-04 8:57,3,중랑센터,7.0,10.0,NaN,32
3,SPB-22292,2019-11-05 8:34,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-05 8:45,3,중랑센터,NaN,10.0,1380.0,21
4,SPB-07935,2019-11-05 12:29,512,뚝섬역 1번 출구 옆,11.0,2019-11-05 12:39,3,중랑센터,7.0,10.0,1650.0,120

In [10]:
df.columns

Index(['자전거번호', '대여일시', '대여소번호', '대여소명', '대여거치대', '반납일시', '반납대여소번호', '반납대여소명',
       '반납거치대', '이용시간', '이용거리', '나이'],
      dtype='object')

In [13]:
df['대여소번호'] == 646
df[df['대여소번호'] == 646]
df.loc[df['대여소번호'] == 646]

,자전거번호,대여일시,대여소번호,대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리,나이
0,SPB-23220,2019-11-01 8:48,646,장한평역 1번출구 (국민은행앞),3.0,2019-11-01 9:01,3,중랑센터,7.0,12.0,1100.0,50
1,SPB-16216,2019-11-04 8:38,646,장한평역 1번출구 (국민은행앞),2.0,2019-11-04 8:56,3,중랑센터,2.0,7.0,1420.0,31
2,SPB-21097,2019-11-04 8:46,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-04 8:57,3,중랑센터,7.0,10.0,NaN,32
3,SPB-22292,2019-11-05 8:34,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-05 8:45,3,중랑센터,NaN,10.0,1380.0,21
5,SPB-18401,2019-11-06 8:52,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-06 9:09,3,중랑센터,7.0,11.0,1350.0,30
6,SPB-18350,2019-11-06 8:35,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-06 9:10,3,중랑센터,2.0,9.0,1390.0,26
8,SPB-20220,2019-11-11 8:35,646,장한평역 1번출구 (국민은행앞),2.0,2019-11-11 8:42,3,중랑센터,2.0,6.0,1160.0,53
9,SPB-20102,2019-11-11 9:45,646,장한평역 1번출구 (국민은행앞),8.0,2019-11-11 10:17,3,중랑센터,7.0,30.0,1060.0,54
10,SPB-10000,2019-11-12 8:35,646,장한평역 1번출구 (국민은행앞),8.0,2019-11-12 8:44,3,중랑센터,2.0,8.0,1300.0,30
11,SPB-20145,2019-11-13 8:30,646,장한평역 1번출구 (국민은행앞),9.0,2019-11-13 8:38,3,중랑센터,2.0,NaN,1060.0,34
12,SPB-19057,2019-11-13 8:55,646,장한평역 1번출구 (국민은행앞),4.0,2019-11-13 9:08,3,중랑센터,7.0,11.0,NaN,57
13,SPB-19645,2019-11-14 9:44,646,장한평역 1번출구 (국민은행앞),NaN,2019-11-14 10:01,3,중랑센터,7.0,16.0,1140.0,59
14,SPB-21851,2019-11-14 9:33,646,장한평역 1번출구 (국민은행앞),10.0,2019-11-14 10:02,3,중랑센터,2.0,28.0,1220.0,51
15,SPB-13973,2019-11-15 8:42,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-15 8:50,3,중랑센터,2.0,6.0,1370.0,32
16,SPB-22311,2019-11-18 8:32,646,장한평역 1번출구 (국민은행앞),6.0,2019-11-18 8:39,3,중랑센터,2.0,NaN,1350.0,31
17,SPB-02270,2019-11-18 8:49,646,장한평역 1번출구 (국민은행앞),4.0,2019-11-18 9:01,3,중랑센터,7.0,11.0,1350.0,31
18,SPB-23659,2019-11-21 8:36,646,장한평역 1번출구 (국민은행앞),NaN,2019-11-21 8:44,3,중랑센터,2.0,6.0,1130.0,33
19,SPB-23497,2019-11-21 8:50,646,장한평역 1번출구 (국민은행앞),2.0,2019-11-21 9:04,3,중랑센터,7.0,13.0,1330.0,32
21,SPB-21810,2019-11-25 8:41,646,장한평역 1번출구 (국민은행앞),5.0,2019-11-25 8:49,3,중랑센터,2.0,7.0,1310.0,50
22,SPB-05857,2019-11-26 8:40,646,장한평역 1번출구 (국민은행앞),6.0,2019-11-26 8:48,3,중랑센터,2.0,NaN,1380.0,41
24,SPB-20076,2019-11-28 8:37,646,장한평역 1번출구 (국민은행앞),6.0,2019-11-28 8:44,3,중랑센터,2.0,5.0,1070.0,51

In [14]:
df.columns

Index(['자전거번호', '대여일시', '대여소번호', '대여소명', '대여거치대', '반납일시', '반납대여소번호', '반납대여소명',
       '반납거치대', '이용시간', '이용거리', '나이'],
      dtype='object')

In [15]:
df[df['대여소번호'] == 646][['대여거치대', '반납일시']]
df.loc[df['대여소번호'] == 646, ['대여거치대', '반납일시']]

    대여거치대              반납일시
0     3.0   2019-11-01 9:01
1     2.0   2019-11-04 8:56
2     1.0   2019-11-04 8:57
3     1.0   2019-11-05 8:45
5     1.0   2019-11-06 9:09
6     1.0   2019-11-06 9:10
8     2.0   2019-11-11 8:42
9     8.0  2019-11-11 10:17
10    8.0   2019-11-12 8:44
11    9.0   2019-11-13 8:38
12    4.0   2019-11-13 9:08
13    NaN  2019-11-14 10:01
14   10.0  2019-11-14 10:02
15    1.0   2019-11-15 8:50
16    6.0   2019-11-18 8:39
17    4.0   2019-11-18 9:01
18    NaN   2019-11-21 8:44
19    2.0   2019-11-21 9:04
21    5.0   2019-11-25 8:49
22    6.0   2019-11-26 8:48
24    6.0   2019-11-28 8:44

In [16]:
df[df['대여소번호'] == 646]['이용거리']
print(df[df['대여소번호'] == 646]['이용거리'].isnull())
df[df['대여소번호'] == 646]['이용거리'].isnull().sum()

0     False
1     False
2      True
3     False
5     False
6     False
8     False
9     False
10    False
11    False
12     True
13    False
14    False
15    False
16    False
17    False
18    False
19    False
21    False
22    False
24    False
Name: 이용거리, dtype: bool

np.int64(2)

In [18]:
df[df['대여소번호'] == 646]['이용거리'].fillna(789.789)
df.loc[df['대여소번호'] == 646, '이용거리'].fillna(123.123)

0     1100.000
1     1420.000
2      789.789
3     1380.000
5     1350.000
6     1390.000
8     1160.000
9     1060.000
10    1300.000
11    1060.000
12     789.789
13    1140.000
14    1220.000
15    1370.000
16    1350.000
17    1350.000
18    1130.000
19    1330.000
21    1310.000
22    1380.000
24    1070.000
Name: 이용거리, dtype: float64

In [19]:
df[df['대여소번호'] == 646]['이용거리']
#df.loc[df['대여소번호'] == 646, '이용거리']

0     1100.0
1     1420.0
2        NaN
3     1380.0
5     1350.0
6     1390.0
8     1160.0
9     1060.0
10    1300.0
11    1060.0
12       NaN
13    1140.0
14    1220.0
15    1370.0
16    1350.0
17    1350.0
18    1130.0
19    1330.0
21    1310.0
22    1380.0
24    1070.0
Name: 이용거리, dtype: float64

In [20]:
df.loc[df['대여소번호'] == 646, '이용거리'] = df [df['대여소번호'] == 646]['이용거리'].fillna(789.789)
df [df['대여소번호'] == 646]['이용거리']
#df.loc[df['대여소번호'] == 646, '이용거리'].fillna(123.123)

0     1100.000
1     1420.000
2      789.789
3     1380.000
5     1350.000
6     1390.000
8     1160.000
9     1060.000
10    1300.000
11    1060.000
12     789.789
13    1140.000
14    1220.000
15    1370.000
16    1350.000
17    1350.000
18    1130.000
19    1330.000
21    1310.000
22    1380.000
24    1070.000
Name: 이용거리, dtype: float64