### Quiz-1
* 결측치를 해결하시오
    1. 결측치 제거(행 삭제)
    2. 결측치 치환
        - Gender : Male
        - Married : Yes
        - Dependents : NaN 최빈값으로 변경. '3+'는 3으로 변경
        - Self_Employed : 이전값
        - LoanAmount : 이후값
        - Loan_Amount_Term : 평균값
        - Credit_History : 1.0

In [67]:
#loan-train.csv 파일 읽어오기

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

#### 결측치 확인

In [68]:
#데이터셋 행,열 개수 출력 및 결측치 확인

(614, 13)

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

#### 결측치 제거

In [69]:
#결측치 제거 후 확인

(480, 13)

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

#### 2.결측치 치환
* Gender : Male
* Married : Yes
* Dependents : NaN 최빈값으로 변경. '3+'는 3으로 변경
* Self_Employed : 이전값
* LoanAmount : 이후값
* Loan_Amount_Term : 평균값
* Credit_History : 1.0

In [70]:
#데이터셋 다시 로드 후 진행

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [71]:
# 데이터셋 행, 열 확인 및 결측값 확인

(614, 13)

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [72]:
#Gender 유니크값 확인

array(['Male', 'Female', nan], dtype=object)

In [73]:
# Gender NaN Male 값으로 치환 후 확인

array(['Male', 'Female'], dtype=object)

In [74]:
# Married 치환 전 유니크값 확인

array(['No', 'Yes', nan], dtype=object)

In [75]:
# Married : Yes 치환 후 결과 확인

array(['No', 'Yes'], dtype=object)

In [76]:
# Dependents 변경 전 확인

array(['0', '1', '2', '3+', nan], dtype=object)

In [77]:
# Dependents NaN값 최빈값으로 변경 후 확인

array(['0', '1', '2', '3+'], dtype=object)

In [78]:
# Dependents 3+ -> 3으로 변경 후 확인

array(['0', '1', '2', '3'], dtype=object)

In [79]:
# Self_Employed 변경전 확인

array(['No', 'Yes', nan], dtype=object)

In [80]:
# Self_Employed 이전 값으로 변경 후 확인

array(['No', 'Yes'], dtype=object)

In [81]:
# LoanAmount 변경전 확인

array([ nan, 128.,  66., 120., 141., 267.,  95., 158., 168., 349.,  70.,
       109., 200., 114.,  17., 125., 100.,  76., 133., 115., 104., 315.,
       116., 112., 151., 191., 122., 110.,  35., 201.,  74., 106., 320.,
       144., 184.,  80.,  47.,  75., 134.,  96.,  88.,  44., 286.,  97.,
       135., 180.,  99., 165., 258., 126., 312., 136., 172.,  81., 187.,
       113., 176., 130., 111., 167., 265.,  50., 210., 175., 131., 188.,
        25., 137., 160., 225., 216.,  94., 139., 152., 118., 185., 154.,
        85., 259., 194.,  93., 370., 182., 650., 102., 290.,  84., 242.,
       129.,  30., 244., 600., 255.,  98., 275., 121.,  63., 700.,  87.,
       101., 495.,  67.,  73., 260., 108.,  58.,  48., 164., 170.,  83.,
        90., 166., 124.,  55.,  59., 127., 214., 240.,  72.,  60., 138.,
        42., 280., 140., 155., 123., 279., 192., 304., 330., 150., 207.,
       436.,  78.,  54.,  89., 143., 105., 132., 480.,  56., 159., 300.,
       376., 117.,  71., 490., 173.,  46., 228., 308., 236., 570., 380.,
       296., 156., 103.,  45.,  65.,  53., 360.,  62., 218., 178., 239.,
       405., 148., 190., 149., 153., 162., 230.,  86., 234., 246., 500.,
       186., 119., 107., 209., 208., 243.,  40., 250., 311., 400., 161.,
       196., 324., 157., 145., 181.,  26., 211.,   9., 205.,  36.,  61.,
       146., 292., 142., 350., 496., 253.])

In [82]:
# LoanAmount 이후(다음) 값으로 변경 후 확인

array([128.,  66., 120., 141., 267.,  95., 158., 168., 349.,  70., 109.,
       200., 114.,  17., 125., 100.,  76., 133., 115., 104., 315., 116.,
       112., 151., 191., 122., 110.,  35., 201.,  74., 106., 320., 144.,
       184.,  80.,  47.,  75., 134.,  96.,  88.,  44., 286.,  97., 135.,
       180.,  99., 165., 258., 126., 312., 136., 172.,  81., 187., 113.,
       176., 130., 111., 167., 265.,  50., 210., 175., 131., 188.,  25.,
       137., 160., 225., 216.,  94., 139., 152., 118., 185., 154.,  85.,
       259., 194.,  93., 370., 182., 650., 102., 290.,  84., 242., 129.,
        30., 244., 600., 255.,  98., 275., 121.,  63., 700.,  87., 101.,
       495.,  67.,  73., 260., 108.,  58.,  48., 164., 170.,  83.,  90.,
       166., 124.,  55.,  59., 127., 214., 240.,  72.,  60., 138.,  42.,
       280., 140., 155., 123., 279., 192., 304., 330., 150., 207., 436.,
        78.,  54.,  89., 143., 105., 132., 480.,  56., 159., 300., 376.,
       117.,  71., 490., 173.,  46., 228., 308., 236., 570., 380., 296.,
       156., 103.,  45.,  65.,  53., 360.,  62., 218., 178., 239., 405.,
       148., 190., 149., 153., 162., 230.,  86., 234., 246., 500., 186.,
       119., 107., 209., 208., 243.,  40., 250., 311., 400., 161., 196.,
       324., 157., 145., 181.,  26., 211.,   9., 205.,  36.,  61., 146.,
       292., 142., 350., 496., 253.])

In [83]:
# Loan_Amount_Term 변경전 확인

array([360., 120., 240.,  nan, 180.,  60., 300., 480.,  36.,  84.,  12.])

In [84]:
# Loan_Amount_Term 평균 값으로 변경 후 확인

array([360., 120., 240., 342., 180.,  60., 300., 480.,  36.,  84.,  12.])

In [85]:
# Credit_History 변경전 확인
# Credit_History 1.0  변경 후 확인

[ 1.  0. nan]

array([1., 0.])

In [86]:
# 최종 결과 확인

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64